site_name: Digital Signal Processing 
site_url: https://devnithw.github.io/dsp-python
site_description: A collection of Digital Signal Processing project notebooks using Python

repo_url: https://github.com/devnithw/dsp-python
repo_name: devnithw/dsp-python

theme:
  name: material
  features: 
    - navigation.instant
    - search.suggest
  language: en
  palette:
    primary: black
    accent: indigo

plugins: 
  - mkdocs-jupyter:
      include_source: True
  - search

nav:
  - Home: 'index.md'
  - denoisesignal: 'denoise_signal.ipynb'
  - ecg_conditioning: 'ecg_conditioning.ipynb'
